Feature/40009
sa11616079/javascript-server pull request #13
Opened 2020-11-03 13:59 UTC by sa11616079

Create a file authMoiddleWare.ts inside libs/routes.

Install a dependency 'jsonwebtoken',

Create a middleware 'authMiddleWare' with following:

Accepts two arguments(module and permission type).
Retrieve token from the header 'Authorization' and decode it using .verify method. It will give the details of user.
If no user decoded. Throws an error of 403. Unauthorized Access.
Use the function hasPermission defined earlier in utils for checking the permission.
If permission does not exists, throws error.
 

Sample token for various roles are:

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJTdWNjZXNzaXZlIFRlY2hub2xvZ2llcyIsImlhdCI6MTU0ODY5MDQzNywiZXhwIjoxNTgwNzk3MjU5LCJhdWQiOiJ3d3cuc3VjY2Vzc2l2ZS5pbiIsInN1YiI6IkxlYXJuIGFuZCBJbXBsZW1lbnQiLCJuYW1lIjoiVHJhaW5lZSIsImVtYWlsIjoidHJhaW5lZUBzdWNjZXNzaXZlLnRlY2giLCJyb2xlIjoidHJhaW5lZSIsImp0aSI6ImEwMjBhYTJlLTk1ZDUtNDc5MC05NDAxLWYyMjFlNDBiNjA1MCJ9.-z2lCFkZJaW5ACZurZH2NiAh9VhefjRCvmlDw1X57Rs
{ "iss": "Successive Technologies", "iat": 1548690437, "exp": 1580226437, "aud": "www.successive.in&quot;, "sub": "Learn and Implement", "name": "Trainee", "email": "trainee@successive.tech", "role": "trainee" } key: qwertyuiopasdfghjklzxcvbnm123456
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJTdWNjZXNzaXZlIFRlY2hub2xvZ2llcyIsImlhdCI6MTU0ODY5MDQzNywiZXhwIjoxNTgwNzk3MzkxLCJhdWQiOiJ3d3cuc3VjY2Vzc2l2ZS5pbiIsInN1YiI6IkxlYXJuIGFuZCBJbXBsZW1lbnQiLCJuYW1lIjoiSGVhZCBUcmFpbmVyIiwiZW1haWwiOiJoZWFkLnRyYWluZXJAc3VjY2Vzc2l2ZS50ZWNoIiwicm9sZSI6ImhlYWQtdHJhaW5lciIsImp0aSI6IjhhMjNkNjc1LWY1NjctNDNmMy1iMDQxLWE3YzlkM2VhMzI4ZCJ9.ciRD8ypgm90pOfD5AD2NKKGOnE7Ke4M0ubSNZvQIaKw { "iss": "Successive Technologies", "iat": 1548690437, "exp": 1580226437, "aud": "www.successive.in&quot;, "sub": "Learn and Implement", "name": "Head Trainer", "email": "head.trainer@successive.tech", "role": "head-trainer" } key: qwertyuiopasdfghjklzxcvbnm123456

2020-11-11 12:56 UTC, SHUBHAM-JAIN-SS requested changes

2020-11-11 12:56 UTC, SHUBHAM-JAIN-SS commented on src/libs/routes/authMoiddleWare.ts
> +        if(hasPermission(permissions.getUser,role,permissionType))
use modulename dynamically

2020-11-12 07:54 UTC, SHUBHAM-JAIN-SS requested changes

2020-11-12 07:54 UTC, SHUBHAM-JAIN-SS commented on src/libs/routes/authMoiddleWare.ts
> +        if(hasPermission(moduleName,role,permissionType))
you are passing a string here and expecting an object in your function implemetation

2020-11-12 08:00 UTC, SHUBHAM-JAIN-SS requested changes

2020-11-12 08:00 UTC, SHUBHAM-JAIN-SS commented on src/controllers/trainee/routes.ts
> +    .get(authMoiddleWare('getUser','read'),validationHandler(Validation.get), TraineeController.get)
you are passing a string here and expecting an object in your middleware implementation

2020-11-12 08:06 UTC, sa11616079 commented on src/controllers/trainee/routes.ts
> +    .get(authMoiddleWare('getUser','read'),validationHandler(Validation.get), TraineeController.get)
check it sir again

2020-11-12 09:25 UTC, merged